### PR TITLE
rocketpool: adding holesky testnet

### PR DESCRIPTION
**Pull request by apentori**

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
We could probably get rid of the map since there's no longer disparity between exec layer network name and consensus layer network name.

**Comment by apentori** [comment]
The variables `rocketpool_eth1_network_ids` and `rocketpool_eth1_network_id` doesn't seems to be used, should i remove it ? 
 https://github.com/status-im/infra-role-rocketpool/blob/master/defaults/main.yml#L16

**Comment by jakubgs** [comment]
Yes, that's what I meant in my comment.

**Comment by apentori** [comment]
Variables removed.

Update `infra-rocketpool` to use `rocketpool_eth2_network` instead
* https://github.com/status-im/infra-rocketpool/pull/17

**Review by jakubgs — CHANGES_REQUESTED** [review]
Needs a README update.

**Comment by apentori** [comment]
README updated, network variable renamed to `rocketpool_network` as mention in : 
* https://github.com/status-im/infra-rocketpool/pull/17

**Review by jakubgs — APPROVED** [review]

**Pull request merged**
